# Generated by Django 5.1.3 on 2024-12-06 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
