# Generated by Django 5.1.4 on 2024-12-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_bid_bid_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlisted_by', to='auctions.item'),
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
