# Generated by Django 5.1.4 on 2024-12-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_item_in_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='in_watchlist',
        ),
    ]
